GOOGLE_DRIVE_EBOOK_LIBRRARY_DB_JSON_URL = "https://drive.google.com/uc?export=view&id=1yOKdYd_1ScGnm7PtsW01JYl5FrEqP0Z6&export=download"
CALIBRE_LIBRARY_PATH = "/Users/jerry/files/private/pyrotechnics/ebooks"
HUGO_STATIC_CONTENT_LIBRARY_PATH = "/Users/jerry/Downloads/library.pyrotechny.eu/books"
HUGO_CONTENT_LIBRARY_PATH = "/Users/jerry/src/github.com/xor-gate/pyrotechny.eu/src/content/library"
LIBRARY_EBOOKS_BASE_URL = "/library"
